// Pin Configuration
#define RELAY_MODULE_PIN 8

#define ULTRASONIC_TRIG_PIN 7
#define ULTRASONIC_ECHO_PIN 6

// Ultrasonic Sensor
#define ULTRASONIC_TRIGGER_DIST_IN_CM 20
#define ULTRASONIC_OBJECT_DETECTION_DELAY_IN_MS 1000


